### ISSUE TITLE
Image with Python 3.6

### ISSUE THREAD

**Issue by davidgasquez** [grpc/grpc-docker-library#45]
Hey there! Seems the only Python image available is for Python 2.7. Can we get a Python 3.6 one too? Happy to send a Pull Request if that sounds good! 😄

**Comment by nathanielmanistaatgoogle** [comment]
[Okay then!](https://github.com/grpc/grpc-docker-library/issues/46)

**Comment by nathanielmanistaatgoogle** [comment]
Fixed by [pull request 46](https://github.com/grpc/grpc-docker-library/issues/46).
